apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notifications-ms.fullname" . }}
  labels:
    {{- include "notifications-ms.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "notifications-ms.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "notifications-ms.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z ploshtadka-db-rw 5432; do sleep 2; done']

      containers:
        - name: notifications-ms
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "notifications-ms.fullname" . }}-config
            - secretRef:
                name: {{ .Values.secrets.name }}
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.dbSecretName }}
                  key: uri
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /health/live
              port: http
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
