apiVersion: v1
kind: Service
metadata:
  name: users-ms
  labels:
    {{- include "users-ms.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "users-ms.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
