---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ploshtadka-db-credentials
  namespace: default
spec:
  encryptedData:
    password: AgAij5XKssbCs1GcwUPk+aXU6WVoMjbS8nkYL+Vaz2A4BuVEbQ0RT+9fj5UxarWSa3TkOrJh5me/Qty8JSz3CWOGRMJj5QWSV5T0xbYM/bBjl1wrg0V8xzypDvzTaV7uUHXC5jlkUbxrbANQtGGo2+pyXkRhl2d0CB+g2Vne+BDeHL6lNO+sxiwXTKV4lRPj9n3sI99UQgYUTK/y5nGpxE0JyAw9HmASuIrvwzSvoVVwEdFJeMvlzxS7m5D+KLN7VggQcSwrgOf7n9PfzBAWPzyk5l74GT2q5mRrOs/lZtKQwEGAt/A9JFmYMUBd28FGzXhJyz8Y0+PCgCgblnqb/pcfWSQNznHZa+uO5AUbKPbB+8+6MRdRAAq5WfvmlAwHwszlR9QtcCACCis6U9ArOmPABJdimeAU+215GXSA2V8UasrMs9aBFRYLvMJXDTQH8iNb3HZ+Z+0q/yZtWsabHTAZy2KGCNFfenXtNFdgqhPFN6UT460qvfj/HGhxWEHD+t5GQHeYYH1rg3kwC4L098bnl82jx03gCQ3MyGdrWqk5ZN30RzPP2JXk/FOCQ65C9hRPtOeQben0Oey4M5c92O3HWdFoHEAhn7SKo01jTG94WcezCH6poB9uc7FyY85IQ4+i8bKPAR1xfysYVRYaz+2waetGnNthvT6dnBJm2yyuG7WFnCUW68X8GuxnmFv+//jRGcjg/zMJ/55GcZD8DrWqkJsuPA==
  template:
    metadata:
      name: ploshtadka-db-credentials
      namespace: default
