---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ploshtadka-db-credentials
  namespace: default
spec:
  encryptedData:
    password: AgC3poyMhzbfWEPZL3lPdrQSwTi0KKGmzzBvvj4lpz6LjYExNatMX4GpTq3YQRyiopfkMZMkqv4hjgoAGXOb2ssb20CgYIad0yFcVd/9ylgC1DRzKWAVCst8PURthntyeS+l7nT2C8sSkR6oTa7JfdUyW/JbKKCbiGTHZZhkKVqa0AE/VhHqoXvHnQamZ1Yv4W1/lm/tOnFawfa9gXT3pEKVGoizk9XpFgfDFuZxBrFuqLfBHW5usGs/tGeix4gqlthcb0m5tRgHpyqL3WhwGG3nj5a8VUFRXpUUjaSiwiqMxXxhcX4DefVZIGvoY5g2egmW5gDJiDYZVmsxqy7U7e7fP1oJmJTXr4FF4TbQrVMRYx9Bpr3lrfWtdrzSWBw2oAVRDE0YgTsbQf3/Juhf5IsgW39xZJAmffA/BxJmR13I25FvjT2zSiNtSZDwujAfNk8peQWBpatFIS9zFYQXJO5LfrMaOV9Bjxwk2pknDWSesosHUmaW2NFECY5a/F6jXHmCthMTEWnfbWZfWr0OTj2/zRzzQ2dxxKZyWwfnwdtFVXcgN+1MZiLVEP2rTwCKzt4WkBkET5J4ark9pqhVCQuf16P/Xfqw0gYTW7a73NULpvG+7gUaEKczoDsGQAgG17sYGOPbdxsSwcrfmk61Mn7fHfgpLgoVkZmzRV8do9pKESc8PWpMceVN+Au3M0/dQGy0wLSpB51knhn4IOZG0HCsFnyQGA==
    username: AgAoojDxrrJym2wptHaP52bc8dl7G2j+GKD/gRtzJZTmpfYTVGRf3hs4hCnBNeks1e64Iu1svHrT9JrlPbZY610ulK2wHc/nfFzAQSC/Tm3199iyiYPVmprwU2FwhVeAyI14RSl1exDGx/LlIGHhQa3WCJdObkqdvzbK1a179GuYfA3g0mg8LvCL6hr+SgqxEYvoIYKfVxHgWoQvbJ4Qv0MPQoPzesCl4TfY4Ll8ufqANt9DUeiG2pmIn8U6lnyxI5ee19OAlTyWeOIG+4z8qcK/d3gHcy+eQKhApWd/JIRPO5koSaH5qX2R+GycxI885Zcpgz2ozKvzF5x1KEPF0ZIawJHloALy3wGaTFTqUig3xCYqlRp12DL1c5TkDvgCRDCGyURCnPEc9C9xuLhPAXiC0GdX0YtrnOjmkxASKDc9t83KppV/84V2a7CPNdttKGuV8gq+3IUucZVDYfe6jbhHRgaYgv6A+WyakLkr+Y9BeBwU4/X6pk95x4qgwUWD+o+DU+wh7gPId840WU6Kt7kN3tfzE+c3Ph7607oFN8Q7D1G8W962WcA4FhanFToovVvah1LphaATi+spcvKbfZVbrKpFpQcrPteJwhhFyToVVDHyV/uOG7Y1sj48/8CI/yRgk42TISblg1MymP6/XJ89ieDDukSUr2Iye4URa/I/EyFAWWbPFSOlFbUzCLu2yV1uFFz2O0GCJ3Ln
  template:
    metadata:
      name: ploshtadka-db-credentials
      namespace: default
