---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ploshtadka-db-credentials
  namespace: default
spec:
  encryptedData:
    password: AgAxJyELjMLe1XnBbN52iOmokpAe0r7jDDRw/8wLrYckc1mAXHJXF1D8daUkvEnsmsKqOP6tYIwXJNK17WDWdQLIdiLETrSCoY5zl5q5Nu8bDZu1G3LtQRA8UKgaaUmwDByU8K2M6KVoow/vGHJThdb2pgQcN076o5p6p6MZlqLsZQBN4WqwiH8epk4vaF1c+iPwdoLuhtxU7yoc5sKagRL8dNk0+rCLkS7bDs6/JTIaviHKWNOW0HaMpY9d1CbkO6RDGYzvb1CA2Ekg9NEVR1RGSftJ+ZBaElzeO8vOsfe32mZhzPhZ7g1rn2Gu4f2yksNT2mGgAYq6tBn23n9vU/P4U6YSYb8EWU+3d7FkPR1pMBkNVugQqyw/X2kQMzEUTWPNz4ELLCTdCYVUsldoShoT8DeRfpqN9XM0GBSaaazVbUR3Xze9EUiI5F0ORT3PyeKmma8T7c415MLWQyJJkXB1EYKTj4oRYl/NBqUCCye28RFNjmxIB2F3BXF20hMimOfib1TavRSsPYHPBuZX9TPdPiP/ezDjwQlXvZ22ZJBGPcX/ZQXASYoes7Yry2gb0Lfs/WufLcuwEoNXcX//zNYYJ8BA5wYZU2dNZIG1nsR4Rs0d78L6+qkl9b1GwfvLmCr5igLA3d7boq1zwRYgwNCzv+pJW8lmJ9FvgDuXXsiL6dHYqjhJeIOsMuuoHp2NiIx1vPofoi35msh2iF8pk4QKV1YxfA==
    username: AgCuKUtO/2ioQmw4eCW0skfrWxn6kdZjtOiJzF5O3Py8UXNSGFKL0hi8r7I/6HaB4VDDwFtb6QN85ePngvnZQJol7VwMnMB7enkLPJLV4r7eagfvG+/o2umVyroYD2uZjF8utZsbZfRtjnqWoL1ODVRpNx5fMKq4vXsF7t9jss//HfUhSqJEpaOTS/QpgfERYd+qbYHowGUmwue/nmxrUHF6AFDlUp+pj671KO3nach3maWnRMoiEvPAnfof1I4+h32dIfwd14uWLDyW9WFtbHx8jUcwQovb+4lzWAOP5/QsLORFVxDGN1Z7tb5hJotWWX95GHIJfvrHi97ONTCi/dDB54O+SgKDII41yUnK0OQiVoD/R2uukO2wd0ihz+bUwMdY3XHtyK2mGGGu516Up7DvUbIsE3fMYxKzrkJ8mtZMwSJKnAGBIdxqYUZ7DnnfesmfXIcmEgLpv6Xc2wZwRzwTfLD24ZxxZxhDME6FYlTaWp6Tc0/6wqnO39Xv1XqwzGSaRWJtF/+mbkjDOQ8NkRakZeJ8VVGbHbCRyigHEkjr76My1ga0wsKsEBRNIlRIdqrJLHDeeiYY2bVTq7wqFfuoMH+Xq9JsFXiQgGg1J6mp+NJ3J80b0xycgKRFL6DSQxYE93pY3gSD9m0QOxwd91WmtAOvAlQfQB/Os8MjrytHSFbPgFm4W96xFrCPb120kURKELgAqrIRcayX
  template:
    metadata:
      name: ploshtadka-db-credentials
      namespace: default
