---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notifications-ms-secrets
  namespace: default
spec:
  encryptedData:
    RESEND_API_KEY: AgAiJ5DxzGSGOFO9RPX4ewUgR2Wp1RK6mRzcsHnf4NlRrRUajf9NoGiiqOO1+lUImj5jpRhlbNw0FXfqxEX6eGjASsQPUHLwxfGlED2nmzWgmmXtSd8YN5QSJpyqBbRrd9Bvh7TItrM4XkoIlU50hEK+EqQ+oV8KM9jqFpNS4NIaTWjAf/45TyaFT+6qRXRMQ4KsIrYQWUerMODYkyjRhAbGE6mnCoE4xqNl9oxRuFsSPuaeSqY9G4LHCy6iiW+ST9w42K7CHLoP1oZxK0TMbPrLATJIlhAxLHjrSLsNwKDkAzJ8Ndj+RD9yBc3JXy/b2XqjWqo8bEKw/7eTXJD0x4qSUuKHQzTB3rJP8hnEbSF7pl51e3qj3c6YAS3GjhyhQ5N4dDOUwpQfvbjZwSnFBDQNF67pvBEVmGXwrrgUIne/Ty0cHwFhSXgYK05idsHPxvMIlzcxxL03ZBz75VbH4nYctsYjV7cs8qUTwqGWu7vkBVjmzOif7J2MZR12dB4ua3n0z8v2JZbYlQeyfYOaFBtpcKTkqOUqE3Pjj6olEiYDYNCfsLVDvR8qeqST04nz/q5gDS2ZfZQIIv/P3K+JVVldA+4G8M5dd8ewfIbaeTwyT8ae2Xzh1XToU00Ymy7nSN5rmyS4MbB+3qyOFCeaZ7bJnxvoEA19iVb0N4V1oKrVk5/ZMe7hEu/VasIR6yFXmt/4EIb6MjIzm+8pdvjHqkx5oS2X7rAjgIg9T3NqfrTbQQ0Hub4=
  template:
    metadata:
      name: notifications-ms-secrets
      namespace: default
